# Generated by Django 5.1.4 on 2024-12-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='picture',
            field=models.ImageField(upload_to='anime_pic/'),
        ),
    ]
