# Generated by Django 5.1.4 on 2024-12-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_anime_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='total_episodes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='EpisodeInfo',
        ),
    ]
