# Generated by Django 5.1.4 on 2024-12-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_anime_total_episodes_delete_episodeinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='episode_no',
            field=models.TextField(blank=True, null=True),
        ),
    ]
