# Generated by Django 5.1.4 on 2024-12-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_episode_episode_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='total_episodes',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='episode_no',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
