# Generated by Django 5.1.4 on 2024-12-22 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_animelist_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animelist',
            name='name',
        ),
        migrations.AddField(
            model_name='animelist',
            name='anime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anime', to='base.anime'),
        ),
    ]
