# Generated by Django 5.1.4 on 2024-12-22 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_animelist_anime_alter_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animelist',
            name='anime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animelist', to='base.anime'),
        ),
    ]
