# Generated by Django 5.1.4 on 2025-04-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_animelist_anime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='video_url',
            field=models.URLField(max_length=4000),
        ),
    ]
